name: Github Actions Example
on:
  push:
    branches:
      - feature/*
  pull-request:
    branches:
      - master
      - develop
jobs:
  build:
    name: Sample build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: npm install
      - name: Test project
        run: npm test